### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by ghost** [noir-clojure/noir#29]
Hello, 

there are no examples of using SSL, nor is it mentioned in the docs. Is it supported?

**Comment by ibdknox** [comment]
It was, though it wasn't obvious how you do it. I've added a :jetty-options key to the server options, which can include any of the options for run-jetty: http://clojuredocs.org/ring/ring.adapter.jetty/run-jetty

You'll want the :ssl? one :)

You will have to delete the cached version of 1.2.0 in ~/.m2 in order to download the updated version from Clojars.

Cheers,
Chris.

**Comment by ibdknox** [comment]
Sorry, should have given an explicit example:

(server/start 8080 {:jetty-options {:ssl? true}})

**Comment by ghost** [comment]
Thanks.
