### ISSUE TITLE
Validations on a model

### ISSUE THREAD

**Issue by blakesmith** [noir-clojure/noir#80]
Hello!

Coming from Rails land, I'm used to having validations happening at the model level, and I'm seeking to do something similar with Noir.

I have a validation on my model like so:

``` clojure
(defn valid? [{:keys [title]}]
  (vali/rule (vali/has-value? title)
             [:title "You must have a title"]))
```

When I try to run (valid? {:title "Bill and Ted's Excellent Adventure"}), I get true, but running with title missing, I get:

```
Var noir.validation/*errors* is unbound.
  [Thrown class java.lang.IllegalStateException]
```

I dug into the source a bit, and it seems like noir makes the assumption that validations can only happen inside the context of a request. Is there something conceptually I'm missing? If my database doesn't support data constraints, I run the risk of having bad data sneak in there if it's not coming from a form. Is it possible to re-use noir's validations outside the context of a web request?

Cheers, and thanks a ton for Noir!

Blake

**Comment by ibdknox** [comment]
This seems like a different level of checking than noir.validation was really meant for. The main use-case for the vali stuff is in validating user input, but it sounds like you're trying to validate within the application itself. Barring using the db to insure integrity, I would simply have asserts. One of the utils I use fairly frequently in my code is a (must-have ...) function that simply makes sure that all the keys I expect to be there have values, if they don't, it throws.

Ignoring all of that, you _could_ just bind it yourself at the level of whatever is running your code (since it's not a request):

``` clojure
(binding [noir.validation/*errors* (atom {})]
      (my-daemon-or-whatever))

;;or in macro form

(defmacro with-errors [& body]
  (binding [noir.validation/*errors* (atom {})]
     ~@body))

(with-errors
  (my-awesome-code))
```

It seems reasonable for that macro to exist, so I'll add it to the 1.3.0-alpha :)

**Comment by blakesmith** [comment]
Awesome. I had to throw a backtick (`) before (binding ... to get the macro to work, and everything looks good now. This strategy will work great for my immediate needs - Thanks so much for the help!
